### ISSUE TITLE
help on codes

### ISSUE THREAD

**Issue by mortezamsp** [mhbashari/perpos#2]
باسلام و خسته نباشید و تشکر بابت این ابزار، که بسادگی قابل استفاده است.
خواهشا معنی کدها را هم در فایل راهنما قرار دهید.
مثلا من نمیدانم فرق این دو چیست:
ADV, ADVe
N, Ne

**Comment by mhbashari** [comment]
سلام
ممنون از شما
حرف ای کوچک انگلیسی به معنای کسره ی اضافه است.
